/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TreehouseJFrame;


import Controller.Khach_hang_controller;
import Controller.Nhan_vien_controller;
import Controller.San_pham_controller;
import Model.Khachhang;
import Model.Nhanvien;
import Model.Sanpham;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class HomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrm
     */
    // San pham
    private List<Sanpham> sanphamList = new ArrayList<>();
    private DefaultTableModel tbModelsp;
    private int selectedindexsp;
    ThemsanphamJF themsanphamFrm;

    // Nhan vien
    private List<Nhanvien> nhanvienList = new ArrayList<>();
    private DefaultTableModel tbModelnv;
    private int selectedindexnv;
    ThemnhanvienJF themnhanvienFrm;
    
    // Khach hang
    private List<Khachhang> khachhangList = new ArrayList<>();
    private DefaultTableModel tbModelkh;
    private int selectedindexkh;


    public HomeFrm() {
        initComponents();

        this.setLocationRelativeTo(null); // Hiển thị giữa màn hình 

        // San pham
        sanphamList = new ArrayList<>();
        tbModelsp = (DefaultTableModel) tbsanpham.getModel();
        Hienthidulieusp();
        // Nhan vien
        nhanvienList = new ArrayList<>();
        tbModelnv = (DefaultTableModel) tbnhanvien.getModel();
        Hienthidulieunv();
        
        // Khachhang
        khachhangList = new ArrayList<>();
        tbModelkh =(DefaultTableModel) tbkhachhang.getModel();
        Hienthidulieukh();

        this.setTitle("Trang chủ");
    }
// San pham

    private void Hienthidulieusp() {
        sanphamList = San_pham_controller.Danhsachsp();
        tbModelsp.setRowCount(0);// Reset noi dung trong bang ve 0
        sanphamList.forEach((indexsp) -> {
            tbModelsp.addRow(new Object[]{indexsp.getMasanpham(),
                indexsp.getTensanpham(), indexsp.getHinhanh(), indexsp.getMota(),
                indexsp.getDongia(), indexsp.getSoluong()});
        });
    }

    public void themsanpham(Sanpham sp) {
        San_pham_controller.insert(sp);
//        sanphamList.add(sp); // Them moi san pham vao danh sach
        Hienthidulieusp();
    }
    
// Nhan vien

    private void Hienthidulieunv() {
        nhanvienList = Nhan_vien_controller.Danhsachnv();
        tbModelnv.setRowCount(0);// Reset noi dung trong bang ve 0
        for (Nhanvien indexnv : nhanvienList) {
            tbModelnv.addRow(new Object[]{indexnv.getManhanvien(),
                indexnv.getTennhanvien(), indexnv.getNgaythangnamsinh(), indexnv.getSoCCCD(),
                indexnv.getSodienthoai(), indexnv.getDiachi(), indexnv.getChucvu()});
        }
    }

    public void themnhanvien(Nhanvien nv) {
        Nhan_vien_controller.insert(nv);
        Hienthidulieunv();
    }
// Khachhang
    private void Hienthidulieukh(){
        khachhangList= Khach_hang_controller.Danhsachkh();
        tbModelkh.setRowCount(0);
        for (Khachhang indexkh : khachhangList) {
            tbModelkh.addRow(new Object[]{indexkh.getMakhachhang(),
                indexkh.getTenkhachhang(), indexkh.getNgaythangnamsinh(), 
                indexkh.getSodienthoai(), indexkh.getDiachi()});
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbtimkiemkhachhang = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbkhachhang = new javax.swing.JTable();
        bttimkiemtheomakh = new javax.swing.JButton();
        bttreehousekh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bttimkiemtheotenkh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbtimkiemkhachhang1 = new javax.swing.JLabel();
        btthemnhanvien = new javax.swing.JButton();
        btsuanhanvien = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbnhanvien = new javax.swing.JTable();
        bttimkiemtheomanv = new javax.swing.JButton();
        bttreehousenv = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bttimkiemtheotennv = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbthongtinsanpham = new javax.swing.JLabel();
        btthemsanpham = new javax.swing.JButton();
        btsuasanpham = new javax.swing.JButton();
        btxoasanpham = new javax.swing.JButton();
        bttreehousesp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbsanpham = new javax.swing.JTable();
        bttimkiemtheotensp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttimkiemtheomasp = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbtimkiemkhachhang.setText(" KHÁCH HÀNG - TREE HOUSE");

        tbkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Ngày/ tháng/ năm sinh", "Số điện thoại", "Địa chỉ"
            }
        ));
        jScrollPane3.setViewportView(tbkhachhang);

        bttimkiemtheomakh.setText("Tìm kiếm theo mã");
        bttimkiemtheomakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimkiemtheomakhActionPerformed(evt);
            }
        });

        bttreehousekh.setText("TREE HOUSE");
        bttreehousekh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttreehousekhActionPerformed(evt);
            }
        });

        jLabel2.setText("DANH SÁCH KHÁCH HÀNG");

        bttimkiemtheotenkh.setText("Tìm kiếm theo tên");
        bttimkiemtheotenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimkiemtheotenkhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbtimkiemkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bttreehousekh))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttimkiemtheotenkh)
                                    .addComponent(bttimkiemtheomakh))
                                .addGap(156, 156, 156)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(886, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(244, 244, 244))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbtimkiemkhachhang)
                .addGap(35, 35, 35)
                .addComponent(bttimkiemtheomakh)
                .addGap(32, 32, 32)
                .addComponent(bttimkiemtheotenkh)
                .addGap(47, 47, 47)
                .addComponent(bttreehousekh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1722, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 230, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("KHÁCH HÀNG", jPanel3);

        lbtimkiemkhachhang1.setText("NHÂN VIÊN - TREE HOUSE");

        btthemnhanvien.setText("Thêm nhân viên");
        btthemnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemnhanvienActionPerformed(evt);
            }
        });

        btsuanhanvien.setText("Sửa nhân viên");
        btsuanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuanhanvienActionPerformed(evt);
            }
        });

        tbnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày/ tháng/ năm sinh", "CCCD", "Số điện thoại", "Địa chỉ", "Chức vụ"
            }
        ));
        jScrollPane4.setViewportView(tbnhanvien);

        bttimkiemtheomanv.setText("Tìm kiếm theo mã");
        bttimkiemtheomanv.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bttimkiemtheomanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimkiemtheomanvActionPerformed(evt);
            }
        });

        bttreehousenv.setText("TREE HOUSE");
        bttreehousenv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttreehousenvActionPerformed(evt);
            }
        });

        jLabel3.setText("DANH SÁCH NHÂN VIÊN");

        bttimkiemtheotennv.setText("Tìm kiếm theo tên");
        bttimkiemtheotennv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimkiemtheotennvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lbtimkiemkhachhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btthemnhanvien)
                                    .addComponent(btsuanhanvien)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(bttimkiemtheomanv)
                                        .addGap(50, 50, 50)
                                        .addComponent(bttimkiemtheotennv))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(bttreehousenv)))
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 624, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(612, 612, 612)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbtimkiemkhachhang1)
                        .addGap(29, 29, 29)
                        .addComponent(btthemnhanvien)
                        .addGap(29, 29, 29)
                        .addComponent(btsuanhanvien)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttimkiemtheomanv)
                            .addComponent(bttimkiemtheotennv))
                        .addGap(71, 71, 71)
                        .addComponent(bttreehousenv)))
                .addContainerGap(429, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("NHÂN VIÊN", jPanel4);

        lbthongtinsanpham.setText("SẢN PHẨM - TREE HOUSE");

        btthemsanpham.setText("Thêm sản phẩm");
        btthemsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemsanphamActionPerformed(evt);
            }
        });

        btsuasanpham.setText("Sửa sản phẩm");
        btsuasanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuasanphamActionPerformed(evt);
            }
        });

        btxoasanpham.setText("Xóa sản phẩm");
        btxoasanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoasanphamActionPerformed(evt);
            }
        });

        bttreehousesp.setText("Tree House");
        bttreehousesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttreehousespActionPerformed(evt);
            }
        });

        tbsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Hình ảnh", "Mô tả", "Đơn giá", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tbsanpham);
        if (tbsanpham.getColumnModel().getColumnCount() > 0) {
            tbsanpham.getColumnModel().getColumn(4).setResizable(false);
        }

        bttimkiemtheotensp.setText("Tìm kiếm theo tên");
        bttimkiemtheotensp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimkiemtheotenspActionPerformed(evt);
            }
        });

        jLabel1.setText("DANH SÁCH SẢN PHẨM");

        bttimkiemtheomasp.setText("Tìm kiếm theo mã");
        bttimkiemtheomasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimkiemtheomaspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(bttreehousesp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbthongtinsanpham))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(656, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bttimkiemtheotensp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttimkiemtheomasp))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btsuasanpham)
                                    .addComponent(btxoasanpham))
                                .addGap(191, 191, 191))
                            .addComponent(btthemsanpham))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addGap(247, 247, 247))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbthongtinsanpham)
                .addGap(18, 18, 18)
                .addComponent(btthemsanpham)
                .addGap(33, 33, 33)
                .addComponent(btsuasanpham)
                .addGap(29, 29, 29)
                .addComponent(btxoasanpham)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttimkiemtheotensp)
                    .addComponent(bttimkiemtheomasp))
                .addGap(57, 57, 57)
                .addComponent(bttreehousesp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SẢN PHẨM", jPanel1);

        jLabel16.setText("CHI TIẾT HÓA ĐƠN XUẤT ");

        jButton7.setText("Thêm ");

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        jLabel17.setText("CHI TIẾT HÓA ĐƠN");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jButton10.setText("jButton10");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8)
                            .addComponent(jButton7))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(jButton9)
                                        .addGap(53, 53, 53))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10)
                                        .addGap(118, 118, 118)))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(465, 465, 465)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(880, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton7)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addGap(56, 56, 56)
                        .addComponent(jButton10))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CHI TIẾT HÓA ĐƠN XUẤT", jPanel7);

        jLabel4.setText("HÓA ĐƠN XUẤT ");

        jTextField1.setText("CÂY CẢNH TREE HOUSE");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tên khách hàng: ");

        jLabel6.setText("Ngày");

        jLabel7.setText("Tháng");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Năm");

        jLabel9.setText("Sản phẩm:");

        jLabel10.setText("Mã hóa đơn");

        jLabel11.setText("Tổng tiền");

        jLabel12.setText("Đơn vị vận chuyển");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giao hàng nhanh", "Giao hàng shopee Express", "Giao hàng Viettel" }));

        jLabel13.setText("Mã nhân viên");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(306, 306, 306)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(111, 111, 111)))
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(894, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HÓA ĐƠN XUẤT", jPanel6);

        jLabel14.setText("NHÀ CUNG CẤP - TREE HOUSE");

        jLabel15.setText("DANH SÁCH NHÀ CUNG CẤP");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Số điện thoại", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Thêm nhà cung cấp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm kiếm theo tên");

        jButton4.setText("Tìm kiếm theo mã");

        jButton5.setText("TREE HOUSE");

        jButton6.setText("Xóa nhà cung cấp");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addComponent(jButton4))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton6)
                                            .addComponent(jButton1))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(841, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel14))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(608, 608, 608)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton6)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))
                        .addGap(30, 30, 30)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NHÀ CUNG CẤP", jPanel8);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btthemsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemsanphamActionPerformed
        // TODO add your handling code here:
        themsanphamFrm = new ThemsanphamJF(this, rootPaneCheckingEnabled);
        themsanphamFrm.setVisible(true);
    }//GEN-LAST:event_btthemsanphamActionPerformed

    private void btsuasanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuasanphamActionPerformed
        // TODO add your handling code here:
        selectedindexsp = tbsanpham.getSelectedRow(); // Tra ve so nguyen gia tri chi so hang ta chon sưa
        if (sanphamList.size() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Không có sản phẩm");
        } else if (selectedindexsp < 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Hãy chọn sản phẩm cần thực hiện sửa!");
        } else {
            SuasanphamJF sua = new SuasanphamJF(this, rootPaneCheckingEnabled);
            sua.Suadulieu(sanphamList.get(selectedindexsp));
            sua.setVisible(true);
            Hienthidulieusp();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công.");

        }
    }//GEN-LAST:event_btsuasanphamActionPerformed

    private void btxoasanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoasanphamActionPerformed
        // TODO add your handling code here:
        int removeIndex = tbsanpham.getSelectedRow(); // Lay chi so hang minh chon muon xoa
        if (removeIndex == -1) // Nguoi dung chua chon dong de xoa
        {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn dòng bạn muốn xóa");
        } else if (sanphamList.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, " Không có thông tin để xóa");
        } else {
            String maSP = sanphamList.get(removeIndex).getMasanpham();
            San_pham_controller.delete(maSP);
            JOptionPane.showMessageDialog(rootPane, "Bạn xóa sản phẩm thành công");

            Hienthidulieusp();

        }
    }//GEN-LAST:event_btxoasanphamActionPerformed

    private void bttreehousespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttreehousespActionPerformed
        // TODO add your handling code here:
        Hienthidulieusp();
    }//GEN-LAST:event_bttreehousespActionPerformed

    private void bttimkiemtheotenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemtheotenspActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên sản phẩm cần tìm kiếm");
        if(input.length() > 0) {
            sanphamList = San_pham_controller.TimKiemTheoTen(input);
            if(sanphamList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sản phẩm không tồn tại !");
            } else {
                tbModelsp.setRowCount(0);// Reset noi dung trong bang ve 0
                sanphamList.forEach((indexsp) -> {
                    tbModelsp.addRow(new Object[]{indexsp.getMasanpham(),
                        indexsp.getTensanpham(), indexsp.getHinhanh(), indexsp.getMota(),
                        indexsp.getDongia(), indexsp.getSoluong()});
                });
            }
        }
    }//GEN-LAST:event_bttimkiemtheotenspActionPerformed

    private void bttimkiemtheomakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemtheomakhActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this,"Nhập mã khách hàng cần tìm kiếm");
        if ( input.length()>0){
            khachhangList= Khach_hang_controller.TimKiemTheoMa(input);
            if (khachhangList.isEmpty()){
                JOptionPane.showMessageDialog(this,"Khách hàng không tồn tại!");
                }else{
                tbModelkh.setRowCount(0);// Reset noi dung trong bang ve 0
                khachhangList.forEach((indexkh) -> {
                    tbModelkh.addRow(new Object[]{indexkh.getMakhachhang(),
                        indexkh.getTenkhachhang(), indexkh.getNgaythangnamsinh(),
                        indexkh.getSodienthoai(), indexkh.getDiachi()});
                }); 
            }
        }
    }//GEN-LAST:event_bttimkiemtheomakhActionPerformed

    private void bttreehousekhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttreehousekhActionPerformed
        // TODO add your handling code here:
        Hienthidulieukh();
    }//GEN-LAST:event_bttreehousekhActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void bttreehousenvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttreehousenvActionPerformed
        // TODO add your handling code here:
        Hienthidulieunv();
    }//GEN-LAST:event_bttreehousenvActionPerformed

    private void bttimkiemtheomanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemtheomanvActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập mã nhân viên cần tìm kiếm");
        if(input.length()> 0) {
            nhanvienList = Nhan_vien_controller.TimKiemTheoMaNV(input);
            if(nhanvienList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nhân viên không có trong danh sách !");
            } else {
                tbModelnv.setRowCount(0);// Reset noi dung trong bang ve 0
                nhanvienList.forEach((indexnv) -> {
                    tbModelnv.addRow(new Object[]{indexnv.getManhanvien(),
                        indexnv.getTennhanvien(),indexnv.getNgaythangnamsinh(),
                        indexnv.getSoCCCD(),indexnv.getSodienthoai(),
                        indexnv.getDiachi(), indexnv.getChucvu()});
                });
            }
        }
    }//GEN-LAST:event_bttimkiemtheomanvActionPerformed

    private void btsuanhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuanhanvienActionPerformed
        // TODO add your handling code here:
        selectedindexnv = tbnhanvien.getSelectedRow(); // Tra ve so nguyen gia tri chi so hang ta chon sưa
        if (nhanvienList.size() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                "Không có nhân viên");
        } else if (selectedindexnv < 0) {
            JOptionPane.showMessageDialog(rootPane,
                "Hãy chọn nhân viên cần thực hiện sửa!");
        } else {
            SuanhanvienJF sua = new SuanhanvienJF(this, rootPaneCheckingEnabled);
            sua.Suadulieunv(nhanvienList.get(selectedindexnv));
            sua.setVisible(true);
            Hienthidulieunv();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công.");
        }
    }//GEN-LAST:event_btsuanhanvienActionPerformed

    private void btthemnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemnhanvienActionPerformed
        // TODO add your handling code here:
        ThemnhanvienJF themnhanvien = new ThemnhanvienJF(this, rootPaneCheckingEnabled);
        themnhanvien.setVisible(true);
    }//GEN-LAST:event_btthemnhanvienActionPerformed

    private void bttimkiemtheomaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemtheomaspActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập mã sản phẩm cần tìm kiếm");
        if(input.length() > 0) {
            sanphamList = San_pham_controller.TimKiemTheoMa(input);
            if(sanphamList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sản phẩm không tồn tại !");
            } else {
                tbModelsp.setRowCount(0);// Reset noi dung trong bang ve 0
                sanphamList.forEach((indexsp) -> {
                    tbModelsp.addRow(new Object[]{indexsp.getMasanpham(),
                        indexsp.getTensanpham(), indexsp.getHinhanh(), indexsp.getMota(),
                        indexsp.getDongia(), indexsp.getSoluong()});
                });
            }
        }
    }//GEN-LAST:event_bttimkiemtheomaspActionPerformed

    private void bttimkiemtheotenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemtheotenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttimkiemtheotenkhActionPerformed

    private void bttimkiemtheotennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemtheotennvActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên nhân viên cần tìm kiếm");
        if(input.length() > 0) {
            nhanvienList = Nhan_vien_controller.TimKiemTheoTenNV(input);
            if(nhanvienList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nhân viên không có trong danh sách !");
            } else {
                tbModelnv.setRowCount(0);// Reset noi dung trong bang ve 0
                nhanvienList.forEach((indexnv) -> {
                    tbModelnv.addRow(new Object[]{indexnv.getManhanvien(),
                        indexnv.getTennhanvien(), indexnv.getNgaythangnamsinh(), 
                        indexnv.getSoCCCD(),indexnv.getSodienthoai(), 
                        indexnv.getDiachi(),indexnv.getChucvu()});
                });
            }
        }
    }//GEN-LAST:event_bttimkiemtheotennvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsuanhanvien;
    private javax.swing.JButton btsuasanpham;
    private javax.swing.JButton btthemnhanvien;
    private javax.swing.JButton btthemsanpham;
    private javax.swing.JButton bttimkiemtheomakh;
    private javax.swing.JButton bttimkiemtheomanv;
    private javax.swing.JButton bttimkiemtheomasp;
    private javax.swing.JButton bttimkiemtheotenkh;
    private javax.swing.JButton bttimkiemtheotennv;
    private javax.swing.JButton bttimkiemtheotensp;
    private javax.swing.JButton bttreehousekh;
    private javax.swing.JButton bttreehousenv;
    private javax.swing.JButton bttreehousesp;
    private javax.swing.JButton btxoasanpham;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbthongtinsanpham;
    private javax.swing.JLabel lbtimkiemkhachhang;
    private javax.swing.JLabel lbtimkiemkhachhang1;
    private javax.swing.JTable tbkhachhang;
    private javax.swing.JTable tbnhanvien;
    private javax.swing.JTable tbsanpham;
    // End of variables declaration//GEN-END:variables

    // San pham
    public void capnhatsanpham(Sanpham sp) {
        San_pham_controller.update(sp);
    }

    // Nhan vien
    public void capnhatnhanvien(Nhanvien nv) {
          Nhan_vien_controller.update(nv);

    }
}
