/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package TreehouseJFrame;

import Model.Nhanvien;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ThemnhanvienJF extends javax.swing.JDialog {

    /**
     * Creates new form ThemnhanvienJF
     */
    private HomeFrm home;
    private String maudinhdang;

    public ThemnhanvienJF(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        home = (HomeFrm) parent;
        this.setTitle("Thêm nhân viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmanhanvien = new javax.swing.JTextField();
        txtngaythangnamsinhnv = new javax.swing.JTextField();
        txtdiachinv = new javax.swing.JTextField();
        btboqua = new javax.swing.JButton();
        btthemnhanvien = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txttennhanvien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcccd = new javax.swing.JTextField();
        txtsodienthoainv = new javax.swing.JTextField();
        cbchucvunv = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtquequan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Ngày/ tháng/ năm sinh");

        jLabel4.setText("CCCD");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Chức vụ");

        txtmanhanvien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmanhanvienFocusLost(evt);
            }
        });
        txtmanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanhanvienActionPerformed(evt);
            }
        });

        btboqua.setText("Bỏ qua");
        btboqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btboquaActionPerformed(evt);
            }
        });

        btthemnhanvien.setText("Thêm nhân viên");
        btthemnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemnhanvienActionPerformed(evt);
            }
        });

        jLabel7.setText("Tên nhân viên:");

        jLabel8.setText("Số điện thoại:");

        txtcccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcccdActionPerformed(evt);
            }
        });

        cbchucvunv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên tư vấn khách hàng", "Nhân viên kế toán", "Nhân viên kho", "Nghỉ làm " }));

        jLabel9.setText("Quê quán");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtquequan)
                            .addComponent(cbchucvunv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmanhanvien)
                            .addComponent(txtdiachinv)
                            .addComponent(txtngaythangnamsinhnv)
                            .addComponent(txttennhanvien)
                            .addComponent(txtcccd)
                            .addComponent(txtsodienthoainv)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btboqua)
                        .addGap(68, 68, 68)
                        .addComponent(btthemnhanvien)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtngaythangnamsinhnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtsodienthoainv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiachinv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbchucvunv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btboqua)
                    .addComponent(btthemnhanvien))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmanhanvienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmanhanvienFocusLost
        // TODO add your handling code here:
        if (this.isVisible()) {
            String manhanvien = txtmanhanvien.getText();
            // Định dạng mã sản phẩm là 2 chữ, 3 sô
            String madinhdang = "^\\w{2}\\d{3}$";
            String dinhdang = String.valueOf(manhanvien.charAt(0)) + String.valueOf(manhanvien.charAt(1));
            if (manhanvien.length() > 0) {
                if (!manhanvien.matches(madinhdang) || !dinhdang.equals("NV")) {
                    JOptionPane.showMessageDialog(rootPane, "Sai định dạng mã nhân viên! ");
                    txtmanhanvien.requestFocus(); // Yeu cau nhap lai không được phép nhập cái khác
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Mã nhân viên không được để trống !");
                txtmanhanvien.requestFocus();
            }
        }
    }//GEN-LAST:event_txtmanhanvienFocusLost

    private void btboquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btboquaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btboquaActionPerformed

    private void btthemnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemnhanvienActionPerformed
        // TODO add your handling code here:
        String manhanvien = "", tennhanvien = "", cccd = "", diachi = "", chucvu = "",
                ngaythangnamsinhnv = "", sodienthoainv = "", quequan = "";
        boolean check = true;
        manhanvien = txtmanhanvien.getText();
        if (txttennhanvien.getText().length() > 0) {
            tennhanvien = txttennhanvien.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên nhân viên");
            check = false;
        }
        if (txtcccd.getText().length() > 0) {
            cccd = txtcccd.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập CCCD");
            check = false;
        }
        if (txtsodienthoainv.getText().length() > 0) {
            sodienthoainv = txtsodienthoainv.getText();
            
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập SÐT");
            check = false;
        }
        if (txtngaythangnamsinhnv.getText().length() > 0) {
            ngaythangnamsinhnv = txtngaythangnamsinhnv.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập ngày sinh");
            check = false;
        }
        if (txtdiachinv.getText().length() > 0) {
            diachi = txtdiachinv.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập địa chỉ");
            check = false;
        }
        if (txtquequan.getText().length() > 0) {
            quequan = txtquequan.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập quê quán");
            check = false;
        }
        chucvu = (String) cbchucvunv.getSelectedItem();

        if(check) {
            Nhanvien nhanvien = new Nhanvien(manhanvien, tennhanvien,
                    ngaythangnamsinhnv, cccd,
                    sodienthoainv, diachi,
                    quequan,chucvu);
            home.themnhanvien(nhanvien);
            JOptionPane.showMessageDialog(rootPane, " Thêm nhân viên thành công!");
        }
        
    }//GEN-LAST:event_btthemnhanvienActionPerformed

    private void txtcccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcccdActionPerformed

    private void txtmanhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanhanvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemnhanvienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemnhanvienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemnhanvienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemnhanvienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemnhanvienJF dialog = new ThemnhanvienJF(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btboqua;
    private javax.swing.JButton btthemnhanvien;
    private javax.swing.JComboBox<String> cbchucvunv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcccd;
    private javax.swing.JTextField txtdiachinv;
    private javax.swing.JTextField txtmanhanvien;
    private javax.swing.JTextField txtngaythangnamsinhnv;
    private javax.swing.JTextField txtquequan;
    private javax.swing.JTextField txtsodienthoainv;
    private javax.swing.JTextField txttennhanvien;
    // End of variables declaration//GEN-END:variables
}
